#spring.profiles.active=dev1
db.url=jdbc:postgresql://localhost:5433/event_dev?useUnicode=yes&characterEncoding=UTF-8
db.user=event_dev
db.password=AA43psxc
salt=ABCD1234EFGH5678
event-dir.temp=C:\\Users\\lars\\application\\event\\
event-type.upload.directory=C:\\Users\\lars\\application\\event\\event-type-upload
#gui-show-session-variables=true