#spring.profiles.active=prod
db.url=jdbc:postgresql://localhost:5432/event?useUnicode=yes&characterEncoding=UTF-8
db.user=event
db.password=AA43psxc
#salt=ABCD1234EFGH5678
#salt=ABCD1234EFGH5678
salt=1A2B3C41234ABCD
event-dir.temp=C:\\apps\\event
event-type.upload.directory=C:\\apps\\event\\upload
gui-show-session-variables=false