#spring.profiles.active=prod
db.url=jdbc:postgresql://localhost:5432/event_test?useUnicode=yes&characterEncoding=UTF-8
db.user=event_test
db.password=test123
salt=ABCD1234EFGH5678

gui-show-session-variables=true

event-dir.temp=C:\\apps\\event
event-type.upload.directory=C:\\apps\\event\\upload