CREATE OR REPLACE VIEW VW_TYPE_AND_TMPL AS
SELECT 
   TYP.ID AS TYP_ID, TYP.LOGIN_ID AS TYP_LOGIN_ID, substring(TYP.NAME,1,20) AS TYP_NAME, substring(TYP.SHORT_NAME,1,10) AS TYP_SHORT,
   TMPL.ID AS TMPL_ID, TMPL.LOGIN_ID AS TMPL_LOGIN, substring(TMPL.NAME, 1, 20) AS TMPL_NAME, 
   substring(TMPL.SHORT_NAME, 1,10) AS TMPL_SHORT, TMPL.IS_FAVORITE AS FAV,
    TMPL.DOSE, TMPL.UNIT
FROM 
   EVENT_TYPE TYP 
      LEFT JOIN EVENT_TEMPLATE TMPL ON TYP.ID = TMPL.EVENT_TYPE_ID 

ORDER BY 
   TYP_ID, TYP_NAME;
   
   
