DROP TABLE IF EXISTS EVENT_STATUS;

DROP TABLE IF EXISTS EVENT_MEDICINE;   
DROP TABLE IF EXISTS EVENT_MEDICINE_TEMPLATE;
DROP TABLE IF EXISTS MEDICINE;
DROP TABLE IF EXISTS MEDICINE_FIRM;


DROP TABLE IF EXISTS EVENT_TREATMENT;   
DROP TABLE IF EXISTS EVENT_TREATMENT_TEMPLATE;
DROP TABLE IF EXISTS TREATMENT;
DROP TABLE IF EXISTS SUPPLYER;

DROP TABLE IF EXISTS EVENT_BASE;
DROP TABLE IF EXISTS EVENT_CATEGORY;

---------------------------------------------------------------

CREATE TABLE EVENT_CATEGORY (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   DESCRIPTION VARCHAR(200)
) ;

CREATE TABLE EVENT_BASE (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   EVENT_CATEGORY_ID INTEGER NOT NULL REFERENCES EVENT_CATEGORY,
      NAME VARCHAR(100) NOT NULL   
) ;
------------------------------------------------------
----- MEDICINE


CREATE TABLE MEDICINE_FIRM (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   BRAND VARCHAR(100) NOT NULL
) ;

CREATE TABLE MEDICINE (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   MEDICINE_FIRM_ID INTEGER NOT NULL REFERENCES MEDICINE_FIRM,
   NAME VARCHAR(100) NOT NULL,
   UNIT VARCHAR(100) NOT NULL,
   DOSE VARCHAR(100) NOT NULL   
) ;

CREATE TABLE EVENT_MEDICINE_TEMPLATE (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   MEDICINE_ID INTEGER NOT NULL REFERENCES MEDICINE,
   MEDICINE_NAME VARCHAR(100) NOT NULL,   
   UNIT VARCHAR(100) NOT NULL,
   DOSE VARCHAR(100) NOT NULL,
   IS_FAVOURITE BOOLEAN 
) ;

CREATE TABLE EVENT_MEDICINE (
   ID SERIAL PRIMARY KEY,
   EVENT_ID INTEGER NOT NULL REFERENCES EVENT_BASE, 
   EVENT_TYPE CHAR(8) DEFAULT 'MEDICINE',
   MEDICINE_ID INTEGER NOT NULL REFERENCES MEDICINE,
   EVENT_MEDICINE_TEMPLATE_ID INTEGER REFERENCES EVENT_MEDICINE_TEMPLATE,   
   UNIT VARCHAR(100) NOT NULL,
   DOSE VARCHAR(100) NOT NULL   
) ;

------------------------------------------------------
----- TREATMENT



CREATE TABLE SUPPLYER (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   BRAND VARCHAR(100) NOT NULL   
) ;


CREATE TABLE TREATMENT (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   SUPPLYER_ID INTEGER NOT NULL REFERENCES SUPPLYER,
   NAME VARCHAR(100) NOT NULL,
   DESCRIPTION VARCHAR(100) NOT NULL   
) ;

CREATE TABLE EVENT_TREATMENT_TEMPLATE (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   EVENT_ID INTEGER NOT NULL REFERENCES EVENT_BASE, 
   TREATMENT_ID INTEGER NOT NULL REFERENCES TREATMENT,  
   NAME VARCHAR(100) NOT NULL
   
) ;
   

CREATE TABLE EVENT_TREATMENT (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   EVENT_ID INTEGER NOT NULL REFERENCES EVENT_BASE, 
   EVENT_TYPE CHAR(9) DEFAULT 'TREATMENT',
   TREATMENT_ID INTEGER NOT NULL REFERENCES TREATMENT,
   EVENT_TREATMENT_TEMPLATE_ID INTEGER REFERENCES EVENT_TREATMENT_TEMPLATE,   
   NAME VARCHAR(100) NOT NULL,
   UNIT VARCHAR(100) NOT NULL,
   DURATION SMALLINT NOT NULL,
   RATING SMALLINT NOT NULL
) ;


------------------------------------------------------
----- STATUS

CREATE TABLE EVENT_STATUS (
   ID SERIAL PRIMARY KEY,
   OWNER_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED_TS TIMESTAMP DEFAULT NOW(),
   EVENT_ID INTEGER NOT NULL REFERENCES EVENT_BASE, 
   EVENT_TYPE CHAR(6) DEFAULT 'STATUS',
   STATUS VARCHAR(300) NOT NULL,
   RATING SMALLINT NOT NULL
) ;















--########################################################

--CREATE TABLE EVENT_TEMPLATE (
--   ID SERIAL PRIMARY KEY ,
--   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
--   CREATED TIMESTAMP DEFAULT NOW(),
--   EVENT_TYPE_ID INTEGER NOT NULL REFERENCES EVENT_TYPE,
--   NAME VARCHAR(100) NOT NULL,
--   SHORT_NAME VARCHAR(20) NOT NULL,
--   DESCRIPTION VARCHAR(200),
--   DOSE VARCHAR(50) NOT NULL,
--   UNIT VARCHAR(30) NOT NULL,
--   SORT_ORDER INTEGER,
--   IS_FAVORITE BOOLEAN, 
--   UNIQUE (login_id, event_type_id, name, unit, dose)
--) ;
--
--
--CREATE TABLE EVENT (
--   ID SERIAL PRIMARY KEY,
--   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
--   CREATED TIMESTAMP DEFAULT NOW(),
--   EVENT_TEMPLATE_ID INTEGER NOT NULL REFERENCES EVENT_TEMPLATE,
--   NAME VARCHAR(100) NOT NULL,
--   SHORT_NAME VARCHAR(40) NOT NULL,
--   DESCRIPTION VARCHAR(200) NOT NULL,
--   DOSE VARCHAR(50) NOT NULL,
--   UNIT VARCHAR(30) NOT NULL,
--   NOTE VARCHAR(100),
--   EVENT_TS TIMESTAMP ,
--   UNIQUE (event_ts,login_id, event_template_id, name, unit, dose )
--) ;



