DROP TABLE IF EXISTS MEDICINE_FIRM CASCADE;
DROP TABLE IF EXISTS MEDICINE_FORM CASCADE;
DROP TABLE IF EXISTS MEDICINE_TYPE CASCADE;
DROP TABLE IF EXISTS MEDICINE CASCADE;
DROP TABLE IF EXISTS MEDICINE_EVENT CASCADE;
DROP TABLE IF EXISTS EVENT_MEDICINE CASCADE;   
DROP TABLE IF EXISTS EVENT_MEDICINE_TEMPLATE CASCADE;
DROP TABLE IF EXISTS BASE_EVENT CASCADE;
DROP TABLE IF EXISTS EVENT_BASE CASCADE;
DROP TABLE IF EXISTS EVENT_CATEGORY CASCADE;

---------------------------------------------------------------
