DROP TABLE IF EXISTS TREATMENT CASCADE;   
DROP TABLE IF EXISTS EVENT_TREATMENT CASCADE;
DROP TABLE IF EXISTS EVENT_TREATMENT_TEMPLATE CASCADE;
DROP TABLE IF EXISTS SUPPLYER CASCADE;

DROP TABLE IF EXISTS BASE_EVENT CASCADE;
DROP TABLE IF EXISTS EVENT_CATEGORY CASCADE ;

---------------------------------------------------------------
