CREATE OR REPLACE VIEW VW_EVENT AS
SELECT 
   EV.ID, EV.LOGIN_ID, 
   to_char(EV.CREATED,'YYYYMMDD HH24:MI') as CREATED, 
   substring(EV.NAME,1,20) AS NAME,
   substring(EV.SHORT_NAME,1,10) AS SHORT,   
   EV.EVENT_TEMPLATE_ID AS TMPL_ID, EVENT_TYPE_ID AS TYPE_ID,
   EV.DOSE, EV.UNIT, EV.NOTE 
FROM 
   EVENT EV    
ORDER BY 
   created
   ;
   
