DROP VIEW IF EXISTS VW_EVENT_COUNT;
DROP VIEW IF EXISTS VW_EVENT_ALL;  
DROP VIEW IF EXISTS VW_EVENTS;
DROP VIEW IF EXISTS VW_EVENT_TEMPLATES;
DROP VIEW IF EXISTS VW_EVENT_OVER;
DROP VIEW IF EXISTS VW_STATE;
DROP VIEW IF EXISTS VW_STATE_ASP;   
DROP VIEW IF EXISTS VW_STATE_REG;   