CREATE TABLE TIME_LINE (
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(60) NOT NULL,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL 
) ;

CREATE TABLE TIME_LINE_SLOT (
   ID SERIAL PRIMARY KEY,
   TIME_LINE_ID INTEGER REFERENCES TIME_LINE,
   FROM_DATE DATE NOT NULL,  
   TO_DATE DATE NOT NULL
) ;


CREATE TABLE EVENT_TYPE (
   ID SERIAL PRIMARY KEY,
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DESCRIPTION VARCHAR(200),
   CREATED TIMESTAMP DEFAULT NOW()
) ;

CREATE TABLE EVENT_TEMPLATE (
   ID SERIAL PRIMARY KEY ,
   EVENT_TYPE_ID INTEGER REFERENCES EVENT_TYPE,
   NAME VARCHAR(100) NOT NULL,
   DOSE VARCHAR(30) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   SHORT_NAME VARCHAR(20) NOT NULL,
   DESCRIPTION VARCHAR(200),
   CREATED TIMESTAMP DEFAULT NOW()
) ;

CREATE TABLE EVENT (
   ID SERIAL PRIMARY KEY,
   EVENT_TEMPLATE_ID INTEGER REFERENCES EVENT_TEMPLATE,
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DOSE VARCHAR(30) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   NOTE VARCHAR(100),
   EVENT_DATE TIMESTAMP DEFAULT NOW(),
   CREATED TIMESTAMP DEFAULT NOW()
) ;


