DROP TABLE IF EXISTS LOGIN_EVENT_XX;

DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS EVENT_TEMPLATE;
DROP TABLE IF EXISTS EVENT_TYPE;
DROP TABLE IF EXISTS TIME_LINE_SLOT;
DROP TABLE IF EXISTS TIME_LINE;

