CREATE OR REPLACE VIEW VW_EVENT_TEMPLATES AS
SELECT 
   ETY.ID AS TYPE_ID, ETY.NAME AS ETY_NAME, ETY.SHORT_NAME AS ETY_SHORT,
   ETMP.ID AS TMPL_ID, ETMP.NAME AS ETMP_NAME, ETMP.SHORT_NAME AS ETMP_SHORT
FROM 
   EVENT_TYPE ETY, EVENT_TEMPLATE ETMP
WHERE 
   ETY.ID = ETMP.EVENT_TYPE_ID
ORDER BY 
   ETY_NAME;
   
CREATE OR REPLACE VIEW VW_EVENTS AS
SELECT 
   ETY.ID AS TYPE_ID, ETY.NAME AS ETY_NAME, ETY.SHORT_NAME AS ETY_SHORT,
   ETMP.ID AS TMPL_ID, ETMP.NAME AS ETMP_NAME, ETMP.SHORT_NAME AS ETMP_SHORT,
   E.EVENT_DATE AS E_DATE, E.ID, E.NOTE
FROM 
   EVENT_TYPE ETY, EVENT_TEMPLATE ETMP, EVENT E
WHERE 
   ETY.ID = ETMP.EVENT_TYPE_ID AND ETMP.ID = E.EVENT_TEMPLATE_ID
ORDER BY 
   ETY_NAME;
   