CREATE TABLE TIME_LINE (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   NAME VARCHAR(60) NOT NULL,
   START_DATE DATE NOT NULL,
   END_DATE DATE NOT NULL 
) ;

CREATE TABLE TIME_LINE_SLOT (
   ID SERIAL PRIMARY KEY,
      LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   TIME_LINE_ID INTEGER REFERENCES TIME_LINE,
   FROM_DATE DATE NOT NULL,  
   TO_DATE DATE NOT NULL
) ;


CREATE TABLE EVENT_TYPE (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DESCRIPTION VARCHAR(200),
   CREATED TIMESTAMP DEFAULT NOW()
) ;

CREATE TABLE EVENT_TEMPLATE (
   ID SERIAL PRIMARY KEY ,
   EVENT_TYPE_ID INTEGER NOT NULL REFERENCES EVENT_TYPE,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   NAME VARCHAR(100) NOT NULL,
   DOSE VARCHAR(30) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   SHORT_NAME VARCHAR(20) NOT NULL,
   DESCRIPTION VARCHAR(200),
   IS_FAVORITE BOOLEAN, 
   SORT_ORDER INTEGER,
   CREATED TIMESTAMP DEFAULT NOW(),
   UNIQUE (login_id, event_type_id, name, unit, dose)
) ;

CREATE TABLE EVENT (
   ID SERIAL PRIMARY KEY,
   EVENT_TEMPLATE_ID INTEGER NOT NULL REFERENCES EVENT_TEMPLATE,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DOSE VARCHAR(30) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   NOTE VARCHAR(100),
   EVENT_DATE TIMESTAMP DEFAULT NOW(),
   CREATED TIMESTAMP DEFAULT NOW(),
   UNIQUE (login_id, event_template_id, name, unit, dose )
) ;


