CREATE TABLE EVENT (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DESCRIPTION VARCHAR(200) NOT NULL,
   EVENT_TEMPLATE_ID INTEGER NOT NULL REFERENCES EVENT_TEMPLATE,
   DOSE NUMERIC(8,2) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   NOTE VARCHAR(100),
   EVENT_TS TIMESTAMP DEFAULT NOW(),
   UNIQUE (event_ts,login_id, event_template_id, name, unit, dose )
) ;


