CREATE TABLE STATE_ASPECT (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(100) NOT NULL,
   DESCRIPTION VARCHAR(600)
   
) ;


