CREATE TABLE EVENT_TEMPLATE (
   ID SERIAL PRIMARY KEY ,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(20) NOT NULL,
   DESCRIPTION VARCHAR(200),
   EVENT_TYPE_ID INTEGER NOT NULL REFERENCES EVENT_TYPE,
   DOSE NUMERIC(8,2) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   IS_FAVORITE BOOLEAN, 
   SORT_ORDER INTEGER,
   UNIQUE (login_id, event_type_id, name, unit, dose)
) ;
