CREATE TABLE EVENT_TYPE (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DESCRIPTION VARCHAR(200)
) ;
