
CREATE TABLE USER_PROFILE (
   ID SERIAL PRIMARY KEY,
   START_TS TIMESTAMP NOT NULL DEFAULT NOW(),
   END_TS TIMESTAMP,
   FIRST_NAME VARCHAR(60) NOT NULL,
   LAST_NAME VARCHAR(60) NOT NULL,
   PRIMARY_PHONE VARCHAR(60),
   PRIMARY_EMAIL VARCHAR(60),
   PRIMARY_STREET_1 VARCHAR(100),
   PRIMARY_STREET_2 VARCHAR(100),
   PRIMARY_POSTAL_CODE VARCHAR(6),
   PRIMARY_CITY VARCHAR(100),
   PRIMARY_COUNTRY VARCHAR(50)
) ;

   
CREATE TABLE LOGIN (
   ID SERIAL PRIMARY KEY,
   START_TS TIMESTAMP NOT NULL DEFAULT NOW(),
   END_TS TIMESTAMP, 
   USER_PROFILE_ID INTEGER REFERENCES USER_PROFILE,
   ROLE VARCHAR(10) NOT NULL,
   LOGIN VARCHAR(60) UNIQUE NOT NULL
);

CREATE TABLE PASSWORD (
   ID SERIAL PRIMARY KEY,
   START_TS TIMESTAMP NOT NULL DEFAULT NOW(),
   END_TS TIMESTAMP,
   LOGIN_ID INTEGER REFERENCES LOGIN, 
   PWD VARCHAR(150) NOT NULL
);



