DROP TABLE IF EXISTS PASSWD;
DROP TABLE IF EXISTS PASSWORD CASCADE;
DROP TABLE IF EXISTS USER_LOGIN;
DROP TABLE IF EXISTS LOGIN CASCADE;
DROP TABLE IF EXISTS LOGIN_USER;
DROP TABLE IF EXISTS USER_PROFILE CASCADE;
DROP TABLE IF EXISTS USER_LOGIN_TOKEN;
DROP TABLE IF EXISTS EVENT_ROLE;


DROP TYPE TYPE_EVENT_ROLE;



