CREATE TABLE STATE_RATING (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   STATE_ASPECT_ID INTEGER NOT NULL REFERENCES STATE_ASPECT,
   STATE_REGISTRATION_ID INTEGER NOT NULL REFERENCES STATE_REGISTRATION,
   RATING INTEGER NOT NULL,
   UNIQUE (login_id, state_aspect_id, state_registration_id)
) ;



