DROP TABLE IF EXISTS EVENT;
DROP TABLE IF EXISTS EVENT_TEMPLATE;
DROP TABLE IF EXISTS EVENT_TYPE;


CREATE TABLE EVENT_TYPE (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DESCRIPTION VARCHAR(200)
) ;

CREATE TABLE EVENT_TEMPLATE (
   ID SERIAL PRIMARY KEY ,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   EVENT_TYPE_ID INTEGER NOT NULL REFERENCES EVENT_TYPE,
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(20) NOT NULL,
   DESCRIPTION VARCHAR(200),
   DOSE VARCHAR(50) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   SORT_ORDER INTEGER,
   IS_FAVORITE BOOLEAN, 
   UNIQUE (login_id, event_type_id, name, unit, dose)
) ;


CREATE TABLE EVENT (
   ID SERIAL PRIMARY KEY,
   LOGIN_ID INTEGER NOT NULL REFERENCES LOGIN,
   CREATED TIMESTAMP DEFAULT NOW(),
   EVENT_TEMPLATE_ID INTEGER NOT NULL REFERENCES EVENT_TEMPLATE,
   NAME VARCHAR(100) NOT NULL,
   SHORT_NAME VARCHAR(40) NOT NULL,
   DESCRIPTION VARCHAR(200) NOT NULL,
   DOSE VARCHAR(50) NOT NULL,
   UNIT VARCHAR(30) NOT NULL,
   NOTE VARCHAR(100),
   EVENT_TS TIMESTAMP ,
   UNIQUE (event_ts,login_id, event_template_id, name, unit, dose )
) ;



