DROP VIEW IF EXISTS VW_EVENT_COUNT;
DROP VIEW IF EXISTS VW_EVENT_ALL;  
DROP VIEW IF EXISTS VW_EVENT;
DROP VIEW IF EXISTS VW_EVENT_TEMPLATES;
DROP VIEW IF EXISTS VW_EVENT_TYPES;
DROP VIEW IF EXISTS VW_EVENT_OVER;
--DROP VIEW IF EXISIS VV_USER_LOGIN;